[tools]
1password-cli = "latest"
antigravity-cli = "latest"
"aqua:go-task/task" = "latest"
"aqua:stripe/stripe-cli" = "latest"
awscli = "latest"
babashka = "latest"
bun = "latest"
chezmoi = "latest"
cmake = "3.31.5"
codex = "latest"
direnv = "latest"
dive = "latest"
duckdb = "latest"
fd = "latest"
glow = "latest"
go = "latest"
helix = "latest"
hurl = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
lazygit = "latest"
node = "22"
opencode = "latest"
python = "3.14"
rust = "latest"
uv = "latest"
yarn = "latest"
yazi = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
