;;; github-light-contrast-theme.el --- GitHub Light Contrast custom theme -*- lexical-binding: t -*-

;;; Commentary:
;; A local light theme inspired by GitHub Light High Contrast.

;;; Code:

(deftheme github-light-contrast
  "GitHub Light Contrast inspired custom theme.")

(let* ((gui-class '((type graphic) (class color) (min-colors 89)))
       (tty-class '((type tty) (class color) (min-colors 256)))
       (fg "#1f2328")
       (fg-muted "#57606a")
       (fg-subtle "#6e7781")
       (comment-fg "#3d444d")
       (comment-delimiter-fg "#4f5863")
       (bg "#ffffff")
       (bg-subtle "#f6f8fa")
       (bg-canvas-inset "#f6f8fa")
       (border "#d0d7de")
       (blue "#0550ae")
       (green "#1a7f37")
       (orange "#9a6700")
       (red "#cf222e")
       (purple "#8250df")
       (cyan "#1b7c83")
       (yellow-bg "#fff1b8")
       (green-bg "#ddf4ff")
       (purple-bg "#fbefff")
       (selection "#cce5ff")
       (current-line "#f6f8fa")
       (tty-fg "color-234")
       (tty-fg-muted "color-240")
       (tty-fg-subtle "color-244")
       (tty-comment-fg "color-238")
       (tty-comment-delimiter-fg "color-243")
       (tty-bg "color-231")
       (tty-bg-subtle "color-255")
       (tty-border "color-251")
       (tty-blue "color-25")
       (tty-green "color-28")
       (tty-orange "color-130")
       (tty-red "color-124")
       (tty-purple "color-91")
       (tty-cyan "color-30")
       (tty-yellow-bg "color-230")
       (tty-green-bg "color-195")
       (tty-purple-bg "color-225")
       (tty-selection "color-153")
       (tty-current-line "color-255"))
  (custom-theme-set-faces
   'github-light-contrast

   `(default ((,gui-class (:foreground ,fg :background ,bg))
              (,tty-class (:foreground ,tty-fg :background ,tty-bg))))
   `(cursor ((,gui-class (:background ,fg)))
             (,tty-class (:background ,tty-fg))))
   `(fringe ((,gui-class (:background ,bg :foreground ,fg-subtle))
             (,tty-class (:background ,tty-bg :foreground ,tty-fg-subtle))))
   `(region ((,gui-class (:background ,selection :foreground ,fg))
             (,tty-class (:background ,tty-selection :foreground ,tty-fg))))
   `(highlight ((,gui-class (:background ,bg-subtle))
                (,tty-class (:background ,tty-bg-subtle))))
   `(hl-line ((,gui-class (:background ,current-line))
              (,tty-class (:background ,tty-current-line))))
   `(minibuffer-prompt ((,gui-class (:foreground ,blue :weight bold))
                        (,tty-class (:foreground ,tty-blue :weight bold))))
   `(vertical-border ((,gui-class (:foreground ,border))
                      (,tty-class (:foreground ,tty-border))))
   `(link ((,gui-class (:foreground ,blue :underline t))
           (,tty-class (:foreground ,tty-blue :underline t))))
   `(link-visited ((,gui-class (:foreground ,purple :underline t))
                   (,tty-class (:foreground ,tty-purple :underline t))))
   `(shadow ((,gui-class (:foreground ,fg-subtle))
             (,tty-class (:foreground ,tty-fg-subtle))))
   `(success ((,gui-class (:foreground ,green :weight semi-bold))
              (,tty-class (:foreground ,tty-green :weight semi-bold))))
   `(warning ((,gui-class (:foreground ,orange :weight semi-bold))
              (,tty-class (:foreground ,tty-orange :weight semi-bold))))
   `(error ((,gui-class (:foreground ,red :weight semi-bold))
            (,tty-class (:foreground ,tty-red :weight semi-bold))))

   `(mode-line ((,gui-class (:background ,bg-subtle :foreground ,fg :box (:line-width 1 :color ,border)))
                (,tty-class (:background ,tty-bg-subtle :foreground ,tty-fg :box (:line-width 1 :color ,tty-border)))))
   `(mode-line-inactive ((,gui-class (:background ,bg :foreground ,fg-muted :box (:line-width 1 :color ,border)))
                         (,tty-class (:background ,tty-bg :foreground ,tty-fg-muted :box (:line-width 1 :color ,tty-border)))))
   `(mode-line-buffer-id ((,gui-class (:weight bold))
                          (,tty-class (:weight bold))))

   `(header-line ((,gui-class (:background ,bg-subtle :foreground ,fg :box (:line-width 1 :color ,border)))
                  (,tty-class (:background ,tty-bg-subtle :foreground ,tty-fg :box (:line-width 1 :color ,tty-border)))))
   `(line-number ((,gui-class (:background ,bg :foreground ,fg-subtle))
                  (,tty-class (:background ,tty-bg :foreground ,tty-fg-subtle))))
   `(line-number-current-line ((,gui-class (:background ,bg :foreground ,fg :weight semi-bold))
                               (,tty-class (:background ,tty-bg :foreground ,tty-fg :weight semi-bold))))

   `(show-paren-match ((,gui-class (:background ,selection :foreground ,fg :weight bold))
                       (,tty-class (:background ,tty-selection :foreground ,tty-fg :weight bold))))
   `(show-paren-mismatch ((,gui-class (:background ,red :foreground ,bg :weight bold))
                          (,tty-class (:background ,tty-red :foreground ,tty-bg :weight bold))))

   `(font-lock-keyword-face ((,gui-class (:foreground ,red :weight semi-bold))
                             (,tty-class (:foreground ,tty-red :weight semi-bold))))
   `(font-lock-builtin-face ((,gui-class (:foreground ,purple))
                             (,tty-class (:foreground ,tty-purple))))
   `(font-lock-function-name-face ((,gui-class (:foreground ,purple :weight semi-bold))
                                   (,tty-class (:foreground ,tty-purple :weight semi-bold))))
   `(font-lock-variable-name-face ((,gui-class (:foreground ,fg))
                                   (,tty-class (:foreground ,tty-fg))))
   `(font-lock-type-face ((,gui-class (:foreground ,orange :weight semi-bold))
                          (,tty-class (:foreground ,tty-orange :weight semi-bold))))
   `(font-lock-constant-face ((,gui-class (:foreground ,purple :background ,purple-bg))
                              (,tty-class (:foreground ,tty-purple :background ,tty-yellow-bg))))
   `(font-lock-string-face ((,gui-class (:foreground ,green))
                            (,tty-class (:foreground ,tty-green))))
   `(font-lock-doc-face ((,gui-class (:foreground ,green))
                         (,tty-class (:foreground ,tty-green))))
   `(font-lock-comment-face ((,gui-class (:foreground ,comment-fg :background ,yellow-bg :slant italic))
                             (,tty-class (:foreground ,tty-comment-fg :background ,tty-yellow-bg :slant italic))))
   `(font-lock-comment-delimiter-face ((,gui-class (:foreground ,comment-delimiter-fg :background ,yellow-bg :slant italic))
                                       (,tty-class (:foreground ,tty-comment-delimiter-fg :background ,tty-yellow-bg :slant italic))))
   `(font-lock-warning-face ((,gui-class (:foreground ,orange :weight semi-bold))
                             (,tty-class (:foreground ,tty-orange :weight semi-bold))))
   `(font-lock-preprocessor-face ((,gui-class (:foreground ,red))
                                  (,tty-class (:foreground ,tty-red))))

   `(isearch ((,gui-class (:background ,yellow-bg :foreground ,fg :weight bold))
              (,tty-class (:background ,tty-yellow-bg :foreground ,tty-fg :weight bold))))
   `(lazy-highlight ((,gui-class (:background ,green-bg :foreground ,fg))
                     (,tty-class (:background ,tty-green-bg :foreground ,tty-fg))))
   `(match ((,gui-class (:background ,green-bg :foreground ,fg))
            (,tty-class (:background ,tty-green-bg :foreground ,tty-fg))))

   `(completions-common-part ((,gui-class (:foreground ,blue :weight semi-bold))
                              (,tty-class (:foreground ,tty-blue :weight semi-bold))))
   `(icomplete-first-match ((,gui-class (:foreground ,blue :weight semi-bold))
                            (,tty-class (:foreground ,tty-blue :weight semi-bold))))

   `(diff-added ((,gui-class (:foreground ,green :background "#dafbe1"))
                 (,tty-class (:foreground ,tty-green :background "color-194"))))
   `(diff-removed ((,gui-class (:foreground ,red :background "#ffebe9"))
                   (,tty-class (:foreground ,tty-red :background "color-224"))))
   `(diff-changed ((,gui-class (:foreground ,orange :background "#fff8c5"))
                   (,tty-class (:foreground ,tty-orange :background ,tty-yellow-bg))))
   `(diff-context ((,gui-class (:foreground ,fg-muted))
                   (,tty-class (:foreground ,tty-fg-muted))))
   `(diff-file-header ((,gui-class (:background ,bg-subtle :foreground ,fg :weight bold))
                       (,tty-class (:background ,tty-bg-subtle :foreground ,tty-fg :weight bold))))
   `(diff-hunk-header ((,gui-class (:background ,bg-canvas-inset :foreground ,fg-muted))
                       (,tty-class (:background ,tty-bg-subtle :foreground ,tty-fg-muted))))

   `(magit-section-heading ((,gui-class (:foreground ,blue :weight bold))
                            (,tty-class (:foreground ,tty-blue :weight bold))))
   `(magit-branch-local ((,gui-class (:foreground ,blue))
                         (,tty-class (:foreground ,tty-blue))))
   `(magit-branch-remote ((,gui-class (:foreground ,green))
                          (,tty-class (:foreground ,tty-green))))
   `(magit-diff-added ((,gui-class (:foreground ,green :background "#dafbe1"))
                       (,tty-class (:foreground ,tty-green :background "color-194"))))
   `(magit-diff-removed ((,gui-class (:foreground ,red :background "#ffebe9"))
                         (,tty-class (:foreground ,tty-red :background "color-224"))))
   `(magit-diff-context-highlight ((,gui-class (:background ,bg-subtle :foreground ,fg-muted))
                                   (,tty-class (:background ,tty-bg-subtle :foreground ,tty-fg-muted))))
   `(magit-diff-hunk-heading ((,gui-class (:background ,bg-subtle :foreground ,fg-muted))
                              (,tty-class (:background ,tty-bg-subtle :foreground ,tty-fg-muted))))
   `(magit-diff-hunk-heading-highlight ((,gui-class (:background ,selection :foreground ,fg))
                                        (,tty-class (:background ,tty-selection :foreground ,tty-fg))))

   `(org-level-1 ((,gui-class (:foreground ,fg :weight bold :height 1.15))
                  (,tty-class (:foreground ,tty-fg :weight bold))))
   `(org-level-2 ((,gui-class (:foreground ,fg :weight bold))
                  (,tty-class (:foreground ,tty-fg :weight bold))))
   `(org-level-3 ((,gui-class (:foreground ,fg))
                  (,tty-class (:foreground ,tty-fg))))
   `(org-block ((,gui-class (:background ,bg-subtle :extend t))
                (,tty-class (:background ,tty-bg-subtle :extend t))))
   `(org-code ((,gui-class (:foreground ,purple :background ,purple-bg))
               (,tty-class (:foreground ,tty-purple :background ,tty-yellow-bg))))
   `(org-verbatim ((,gui-class (:foreground ,purple :background ,purple-bg))
                   (,tty-class (:foreground ,tty-purple :background ,tty-yellow-bg))))
   `(org-document-title ((,gui-class (:foreground ,fg :weight bold :height 1.2))
                         (,tty-class (:foreground ,tty-fg :weight bold))))

   `(markdown-code-face ((,gui-class (:background ,bg-subtle :extend t))
                         (,tty-class (:background ,tty-bg-subtle :extend t))))

   `(company-tooltip ((,gui-class (:background ,bg-subtle :foreground ,fg))
                      (,tty-class (:background ,tty-bg-subtle :foreground ,tty-fg))))
   `(company-tooltip-selection ((,gui-class (:background ,selection :foreground ,fg))
                                (,tty-class (:background ,tty-selection :foreground ,tty-fg))))
   `(company-tooltip-common ((,gui-class (:foreground ,blue :weight semi-bold))
                             (,tty-class (:foreground ,tty-blue :weight semi-bold))))

   `(vterm-color-black ((,gui-class (:foreground ,fg-muted :background ,fg-muted))
                        (,tty-class (:foreground ,tty-fg-muted :background ,tty-fg-muted))))
   `(vterm-color-red ((,gui-class (:foreground ,red :background ,red))
                      (,tty-class (:foreground ,tty-red :background ,tty-red))))
   `(vterm-color-green ((,gui-class (:foreground ,green :background ,green))
                        (,tty-class (:foreground ,tty-green :background ,tty-green))))
   `(vterm-color-yellow ((,gui-class (:foreground ,orange :background ,orange))
                         (,tty-class (:foreground ,tty-orange :background ,tty-orange))))
   `(vterm-color-blue ((,gui-class (:foreground ,blue :background ,blue))
                       (,tty-class (:foreground ,tty-blue :background ,tty-blue))))
   `(vterm-color-magenta ((,gui-class (:foreground ,purple :background ,purple))
                          (,tty-class (:foreground ,tty-purple :background ,tty-purple))))
   `(vterm-color-cyan ((,gui-class (:foreground ,cyan :background ,cyan))
                       (,tty-class (:foreground ,tty-cyan :background ,tty-cyan))))
   `(vterm-color-white ((,gui-class (:foreground ,bg-subtle :background ,bg-subtle))
                        (,tty-class (:foreground ,tty-bg-subtle :background ,tty-bg-subtle)))))

(provide-theme 'github-light-contrast)

;;; github-light-contrast-theme.el ends here
